[2025-05-07T09:22:45.935+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.get_metrics manual__2025-05-07T09:19:40.127495+00:00 [queued]>
[2025-05-07T09:22:45.939+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.get_metrics manual__2025-05-07T09:19:40.127495+00:00 [queued]>
[2025-05-07T09:22:45.940+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-07T09:22:45.946+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_metrics> on 2025-05-07 09:19:40.127495+00:00
[2025-05-07T09:22:45.953+0000] {standard_task_runner.py:57} INFO - Started process 14115 to run task
[2025-05-07T09:22:45.956+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'lgbtq_model_pipeline', 'get_metrics', 'manual__2025-05-07T09:19:40.127495+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/lgbtq_model_pipeline.py', '--cfg-path', '/tmp/tmpk7k23f_2']
[2025-05-07T09:22:45.966+0000] {standard_task_runner.py:85} INFO - Job 55: Subtask get_metrics
[2025-05-07T09:22:46.040+0000] {task_command.py:416} INFO - Running <TaskInstance: lgbtq_model_pipeline.get_metrics manual__2025-05-07T09:19:40.127495+00:00 [running]> on host 6fdcfcafebfc
[2025-05-07T09:22:46.124+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lgbtq_model_pipeline' AIRFLOW_CTX_TASK_ID='get_metrics' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T09:19:40.127495+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-07T09:19:40.127495+00:00'
[2025-05-07T09:22:46.127+0000] {logging_mixin.py:154} INFO - üìè Evaluating latest models...
[2025-05-07T09:22:46.129+0000] {logging_mixin.py:154} INFO - üì• Loading model from /opt/***/models/production_model_20250507054548.joblib
[2025-05-07T09:23:19.006+0000] {logging_mixin.py:154} WARNING - /opt/***/dags/tasks/get_metrics.py:38 RuntimeWarning: Mean of empty slice.
[2025-05-07T09:23:19.008+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/core/_methods.py:184 RuntimeWarning: invalid value encountered in divide
[2025-05-07T09:23:19.009+0000] {logging_mixin.py:154} WARNING - /opt/***/dags/tasks/get_metrics.py:39 RuntimeWarning: Mean of empty slice.
[2025-05-07T09:23:19.023+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks/get_metrics.py", line 74, in run
    new_acc = evaluate_model(os.path.join(MODEL_DIR, new_model))
  File "/opt/airflow/dags/tasks/get_metrics.py", line 57, in evaluate_model
    pred_labels = classify_from_centroids(embeddings, labels, embeddings, labels)
  File "/opt/airflow/dags/tasks/get_metrics.py", line 41, in classify_from_centroids
    pro_sim = cosine_similarity(embeddings, [pro_centroid]).squeeze()
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/metrics/pairwise.py", line 1578, in cosine_similarity
    X, Y = check_pairwise_arrays(X, Y)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/metrics/pairwise.py", line 173, in check_pairwise_arrays
    Y = check_array(
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 957, in check_array
    _assert_all_finite(
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 122, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 171, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.
[2025-05-07T09:23:19.046+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=lgbtq_model_pipeline, task_id=get_metrics, execution_date=20250507T091940, start_date=20250507T092245, end_date=20250507T092319
[2025-05-07T09:23:19.058+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 55 for task get_metrics (Input contains NaN.; 14115)
[2025-05-07T09:23:19.108+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-07T09:23:19.131+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
