[2025-05-07T02:05:33.305+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.retrain manual__2025-05-07T02:03:12.318823+00:00 [queued]>
[2025-05-07T02:05:33.308+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.retrain manual__2025-05-07T02:03:12.318823+00:00 [queued]>
[2025-05-07T02:05:33.309+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-07T02:05:33.315+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrain> on 2025-05-07 02:03:12.318823+00:00
[2025-05-07T02:05:33.320+0000] {standard_task_runner.py:57} INFO - Started process 1625 to run task
[2025-05-07T02:05:33.323+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'lgbtq_model_pipeline', 'retrain', 'manual__2025-05-07T02:03:12.318823+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/lgbtq_model_pipeline.py', '--cfg-path', '/tmp/tmpe00rhc02']
[2025-05-07T02:05:33.325+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask retrain
[2025-05-07T02:05:33.351+0000] {task_command.py:416} INFO - Running <TaskInstance: lgbtq_model_pipeline.retrain manual__2025-05-07T02:03:12.318823+00:00 [running]> on host ba7fb2e9095e
[2025-05-07T02:05:33.386+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lgbtq_model_pipeline' AIRFLOW_CTX_TASK_ID='retrain' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T02:03:12.318823+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-07T02:03:12.318823+00:00'
[2025-05-07T02:05:33.387+0000] {logging_mixin.py:154} INFO - üì¶ Combining data...
[2025-05-07T02:05:33.661+0000] {logging_mixin.py:154} INFO - ‚ö†Ô∏è Skipping duplicate article_246
[2025-05-07T02:05:33.662+0000] {logging_mixin.py:154} INFO - ‚ö†Ô∏è Skipping duplicate article_247
[2025-05-07T02:05:33.663+0000] {logging_mixin.py:154} INFO - ‚ö†Ô∏è Skipping duplicate article_245
[2025-05-07T02:05:33.663+0000] {logging_mixin.py:154} INFO - ‚ö†Ô∏è Skipping duplicate article_249
[2025-05-07T02:05:33.664+0000] {logging_mixin.py:154} INFO - ‚ö†Ô∏è Skipping duplicate article_248
[2025-05-07T02:05:33.665+0000] {logging_mixin.py:154} INFO - ‚ö†Ô∏è Skipping duplicate article_244
[2025-05-07T02:05:33.665+0000] {logging_mixin.py:154} INFO - üìö Loading labeled data...
[2025-05-07T02:05:33.754+0000] {logging_mixin.py:154} INFO - üß† Preparing triplet training data...
[2025-05-07T02:05:33.755+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/transformers/utils/hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "/home/airflow/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/opt/***/hf_model'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks/retrain.py", line 53, in train_triplet_model
    triplet_dataset = get_triplet_dataset(texts, labels, model_path=HF_MODEL_PATH)
  File "/opt/airflow/dags/model_code/model.py", line 64, in get_triplet_dataset
    tokenizer = AutoTokenizer.from_pretrained(model_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 857, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 689, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/transformers/utils/hub.py", line 469, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: '/opt/***/hf_model'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
[2025-05-07T02:05:33.763+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=lgbtq_model_pipeline, task_id=retrain, execution_date=20250507T020312, start_date=20250507T020533, end_date=20250507T020533
[2025-05-07T02:05:33.769+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task retrain (Incorrect path_or_model_id: '/opt/***/hf_model'. Please provide either the path to a local folder or the repo_id of a model on the Hub.; 1625)
[2025-05-07T02:05:33.790+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-07T02:05:33.803+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
