[2025-05-07T11:23:27.725+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.decide_branch manual__2025-05-07T11:22:56.503702+00:00 [queued]>
[2025-05-07T11:23:27.735+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.decide_branch manual__2025-05-07T11:22:56.503702+00:00 [queued]>
[2025-05-07T11:23:27.742+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-07T11:23:27.765+0000] {taskinstance.py:1382} INFO - Executing <Task(BranchPythonOperator): decide_branch> on 2025-05-07 11:22:56.503702+00:00
[2025-05-07T11:23:27.787+0000] {standard_task_runner.py:57} INFO - Started process 20899 to run task
[2025-05-07T11:23:27.793+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'lgbtq_model_pipeline', 'decide_branch', 'manual__2025-05-07T11:22:56.503702+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/lgbtq_model_pipeline.py', '--cfg-path', '/tmp/tmpk0cznjpn']
[2025-05-07T11:23:27.795+0000] {standard_task_runner.py:85} INFO - Job 133: Subtask decide_branch
[2025-05-07T11:23:27.865+0000] {task_command.py:416} INFO - Running <TaskInstance: lgbtq_model_pipeline.decide_branch manual__2025-05-07T11:22:56.503702+00:00 [running]> on host 6fdcfcafebfc
[2025-05-07T11:23:27.951+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lgbtq_model_pipeline' AIRFLOW_CTX_TASK_ID='decide_branch' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T11:22:56.503702+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-07T11:22:56.503702+00:00'
[2025-05-07T11:23:27.952+0000] {logging_mixin.py:154} INFO - ðŸ‘€ Evaluating model performance...
[2025-05-07T11:23:27.954+0000] {logging_mixin.py:154} INFO - ðŸ”¢ Previous Accuracy: 0.5582
[2025-05-07T11:23:27.955+0000] {logging_mixin.py:154} INFO - ðŸ”¢ New Accuracy:      0.6426
[2025-05-07T11:23:27.955+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 226, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks/branch_decision.py", line 27, in decide_branch
    with open(PROD_TRACKING_PATH) as f:
NameError: name 'PROD_TRACKING_PATH' is not defined
[2025-05-07T11:23:27.975+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=lgbtq_model_pipeline, task_id=decide_branch, execution_date=20250507T112256, start_date=20250507T112327, end_date=20250507T112327
[2025-05-07T11:23:28.002+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 133 for task decide_branch (name 'PROD_TRACKING_PATH' is not defined; 20899)
[2025-05-07T11:23:28.018+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-07T11:23:28.058+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
