[2025-05-07T10:35:59.459+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.deploy_model manual__2025-05-07T10:19:40.711419+00:00 [queued]>
[2025-05-07T10:35:59.466+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.deploy_model manual__2025-05-07T10:19:40.711419+00:00 [queued]>
[2025-05-07T10:35:59.466+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-07T10:35:59.472+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): deploy_model> on 2025-05-07 10:19:40.711419+00:00
[2025-05-07T10:35:59.478+0000] {standard_task_runner.py:57} INFO - Started process 18069 to run task
[2025-05-07T10:35:59.484+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'lgbtq_model_pipeline', 'deploy_model', 'manual__2025-05-07T10:19:40.711419+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/lgbtq_model_pipeline.py', '--cfg-path', '/tmp/tmp0def8jdz']
[2025-05-07T10:35:59.486+0000] {standard_task_runner.py:85} INFO - Job 92: Subtask deploy_model
[2025-05-07T10:35:59.518+0000] {task_command.py:416} INFO - Running <TaskInstance: lgbtq_model_pipeline.deploy_model manual__2025-05-07T10:19:40.711419+00:00 [running]> on host 6fdcfcafebfc
[2025-05-07T10:35:59.582+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lgbtq_model_pipeline' AIRFLOW_CTX_TASK_ID='deploy_model' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T10:19:40.711419+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-07T10:19:40.711419+00:00'
[2025-05-07T10:35:59.585+0000] {logging_mixin.py:154} INFO - ðŸš€ Deploying new model...
[2025-05-07T10:35:59.586+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks/deploy_model.py", line 24, in run
    shutil.copy(NEW_MODEL_PATH, DEPLOYED_MODEL_PATH)
  File "/usr/local/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/models/classifier.joblib'
[2025-05-07T10:35:59.666+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=lgbtq_model_pipeline, task_id=deploy_model, execution_date=20250507T101940, start_date=20250507T103559, end_date=20250507T103559
[2025-05-07T10:35:59.731+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 92 for task deploy_model ([Errno 2] No such file or directory: '/opt/airflow/models/classifier.joblib'; 18069)
[2025-05-07T10:35:59.780+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-07T10:35:59.798+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
