[2025-05-01T09:09:41.545+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.retrain manual__2025-05-01T09:09:15.846373+00:00 [queued]>
[2025-05-01T09:09:41.549+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.retrain manual__2025-05-01T09:09:15.846373+00:00 [queued]>
[2025-05-01T09:09:41.549+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-01T09:09:41.554+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrain> on 2025-05-01 09:09:15.846373+00:00
[2025-05-01T09:09:41.558+0000] {standard_task_runner.py:57} INFO - Started process 241 to run task
[2025-05-01T09:09:41.560+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'lgbtq_model_pipeline', 'retrain', 'manual__2025-05-01T09:09:15.846373+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/lgbtq_model_pipeline.py', '--cfg-path', '/tmp/tmp7m9fzex3']
[2025-05-01T09:09:41.564+0000] {standard_task_runner.py:85} INFO - Job 158: Subtask retrain
[2025-05-01T09:09:41.584+0000] {task_command.py:416} INFO - Running <TaskInstance: lgbtq_model_pipeline.retrain manual__2025-05-01T09:09:15.846373+00:00 [running]> on host a943459b2993
[2025-05-01T09:09:41.617+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lgbtq_model_pipeline' AIRFLOW_CTX_TASK_ID='retrain' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T09:09:15.846373+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-01T09:09:15.846373+00:00'
[2025-05-01T09:09:41.618+0000] {logging_mixin.py:154} INFO - üîÅ Starting retraining process...
[2025-05-01T09:09:41.618+0000] {logging_mixin.py:154} INFO - üì¶ Combining production and new data into all_data...
[2025-05-01T09:09:41.625+0000] {logging_mixin.py:154} INFO - üìä Loading all training data...
[2025-05-01T09:09:41.628+0000] {logging_mixin.py:154} INFO - üß† Retraining classifier on 10 samples...
[2025-05-01T09:09:41.629+0000] {logging_mixin.py:154} INFO - üìÇ Loading previous model from /opt/***/models/classifier.joblib
[2025-05-01T09:09:41.632+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/sklearn/base.py:348 InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.5.1 when using version 1.3.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
[2025-05-01T09:09:41.633+0000] {logging_mixin.py:154} INFO - üõ°Ô∏è Backed up previous model to /opt/***/models/classifier_backup_20250501090941.joblib
[2025-05-01T09:09:41.643+0000] {logging_mixin.py:154} INFO - ‚úÖ Saved retrained classifier to /opt/***/models/classifier.joblib
[2025-05-01T09:09:41.643+0000] {logging_mixin.py:154} INFO - üì¶ Generating predictions for metric evaluation...
[2025-05-01T09:09:41.650+0000] {logging_mixin.py:154} INFO -    y_true  y_pred    y_prob
0       1       1  0.514491
1       1       1  0.515086
2       1       1  0.515086
3       1       1  0.514491
4       0       0  0.334496
[2025-05-01T09:09:41.650+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks/retrain.py", line 108, in run
    print(f"Saving to: {predictions_path}")
UnboundLocalError: local variable 'predictions_path' referenced before assignment
[2025-05-01T09:09:41.656+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=lgbtq_model_pipeline, task_id=retrain, execution_date=20250501T090915, start_date=20250501T090941, end_date=20250501T090941
[2025-05-01T09:09:41.661+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 158 for task retrain (local variable 'predictions_path' referenced before assignment; 241)
[2025-05-01T09:09:41.699+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-01T09:09:41.714+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
