[2025-05-01T08:56:25.494+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.retrain manual__2025-05-01T08:55:46.695685+00:00 [queued]>
[2025-05-01T08:56:25.498+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.retrain manual__2025-05-01T08:55:46.695685+00:00 [queued]>
[2025-05-01T08:56:25.498+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-01T08:56:25.503+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrain> on 2025-05-01 08:55:46.695685+00:00
[2025-05-01T08:56:25.506+0000] {standard_task_runner.py:57} INFO - Started process 280 to run task
[2025-05-01T08:56:25.508+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'lgbtq_model_pipeline', 'retrain', 'manual__2025-05-01T08:55:46.695685+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/lgbtq_model_pipeline.py', '--cfg-path', '/tmp/tmp00oix09r']
[2025-05-01T08:56:25.512+0000] {standard_task_runner.py:85} INFO - Job 150: Subtask retrain
[2025-05-01T08:56:25.531+0000] {task_command.py:416} INFO - Running <TaskInstance: lgbtq_model_pipeline.retrain manual__2025-05-01T08:55:46.695685+00:00 [running]> on host 6119a4f65e6c
[2025-05-01T08:56:25.563+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lgbtq_model_pipeline' AIRFLOW_CTX_TASK_ID='retrain' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T08:55:46.695685+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-01T08:55:46.695685+00:00'
[2025-05-01T08:56:25.563+0000] {logging_mixin.py:154} INFO - üîÅ Starting retraining process...
[2025-05-01T08:56:25.563+0000] {logging_mixin.py:154} INFO - üì¶ Combining production and new data into all_data...
[2025-05-01T08:56:25.564+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks/retrain.py", line 60, in run
    combine_data()
  File "/opt/airflow/dags/tasks/retrain.py", line 23, in combine_data
    for f in os.listdir(PRODUCTION_DATA_DIR):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/production_data'
[2025-05-01T08:56:25.568+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=lgbtq_model_pipeline, task_id=retrain, execution_date=20250501T085546, start_date=20250501T085625, end_date=20250501T085625
[2025-05-01T08:56:25.572+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 150 for task retrain ([Errno 2] No such file or directory: '/opt/airflow/production_data'; 280)
[2025-05-01T08:56:25.607+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-01T08:56:25.622+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
