[2025-05-07T11:36:52.905+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.decide_branch manual__2025-05-07T11:36:39.646877+00:00 [queued]>
[2025-05-07T11:36:52.909+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.decide_branch manual__2025-05-07T11:36:39.646877+00:00 [queued]>
[2025-05-07T11:36:52.909+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-07T11:36:52.915+0000] {taskinstance.py:1382} INFO - Executing <Task(BranchPythonOperator): decide_branch> on 2025-05-07 11:36:39.646877+00:00
[2025-05-07T11:36:52.922+0000] {standard_task_runner.py:57} INFO - Started process 21808 to run task
[2025-05-07T11:36:52.924+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'lgbtq_model_pipeline', 'decide_branch', 'manual__2025-05-07T11:36:39.646877+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/lgbtq_model_pipeline.py', '--cfg-path', '/tmp/tmpp01qiroc']
[2025-05-07T11:36:52.926+0000] {standard_task_runner.py:85} INFO - Job 153: Subtask decide_branch
[2025-05-07T11:36:52.950+0000] {task_command.py:416} INFO - Running <TaskInstance: lgbtq_model_pipeline.decide_branch manual__2025-05-07T11:36:39.646877+00:00 [running]> on host 6fdcfcafebfc
[2025-05-07T11:36:52.986+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lgbtq_model_pipeline' AIRFLOW_CTX_TASK_ID='decide_branch' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T11:36:39.646877+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-07T11:36:39.646877+00:00'
[2025-05-07T11:36:52.987+0000] {logging_mixin.py:154} INFO - ðŸ‘€ Evaluating model performance...
[2025-05-07T11:36:52.987+0000] {logging_mixin.py:154} INFO - ðŸ”¢ Previous Accuracy: 0.6426
[2025-05-07T11:36:52.987+0000] {logging_mixin.py:154} INFO - ðŸ”¢ New Accuracy:      0.6426
[2025-05-07T11:36:52.987+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 226, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks/branch_decision.py", line 27, in decide_branch
    with open(PROD_TRACKING_PATH) as f:
NameError: name 'PROD_TRACKING_PATH' is not defined
[2025-05-07T11:36:52.992+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=lgbtq_model_pipeline, task_id=decide_branch, execution_date=20250507T113639, start_date=20250507T113652, end_date=20250507T113652
[2025-05-07T11:36:52.997+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 153 for task decide_branch (name 'PROD_TRACKING_PATH' is not defined; 21808)
[2025-05-07T11:36:53.024+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-07T11:36:53.040+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
