[2025-05-08T08:13:45.555+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.human_review manual__2025-05-08T08:13:39.037151+00:00 [queued]>
[2025-05-08T08:13:45.564+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lgbtq_model_pipeline.human_review manual__2025-05-08T08:13:39.037151+00:00 [queued]>
[2025-05-08T08:13:45.564+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-08T08:13:45.573+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): human_review> on 2025-05-08 08:13:39.037151+00:00
[2025-05-08T08:13:45.592+0000] {standard_task_runner.py:57} INFO - Started process 3875 to run task
[2025-05-08T08:13:45.601+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'lgbtq_model_pipeline', 'human_review', 'manual__2025-05-08T08:13:39.037151+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/lgbtq_model_pipeline.py', '--cfg-path', '/tmp/tmps08cpd_y']
[2025-05-08T08:13:45.605+0000] {standard_task_runner.py:85} INFO - Job 255: Subtask human_review
[2025-05-08T08:13:45.640+0000] {task_command.py:416} INFO - Running <TaskInstance: lgbtq_model_pipeline.human_review manual__2025-05-08T08:13:39.037151+00:00 [running]> on host 57d75ba4cf3d
[2025-05-08T08:13:45.702+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lgbtq_model_pipeline' AIRFLOW_CTX_TASK_ID='human_review' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T08:13:39.037151+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-08T08:13:39.037151+00:00'
[2025-05-08T08:13:45.703+0000] {logging_mixin.py:154} INFO - üëÄ Checking for enough articles in review queue...
[2025-05-08T08:13:45.708+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/pymongo/synchronous/mongo_client.py:2554 UserWarning: MongoClient opened before fork. May not be entirely fork-safe, proceed with caution. See PyMongo's documentation for details: https://www.mongodb.com/docs/languages/python/pymongo-driver/current/faq/#is-pymongo-fork-safe-
[2025-05-08T08:13:46.360+0000] {logging_mixin.py:154} INFO - ‚è≥ Not enough files (0/5). Waiting.
[2025-05-08T08:13:46.362+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-08T08:13:46.377+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=lgbtq_model_pipeline, task_id=human_review, execution_date=20250508T081339, start_date=20250508T081345, end_date=20250508T081346
[2025-05-08T08:13:46.444+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-08T08:13:46.473+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
